apiVersion: v1
kind: Namespace
metadata:
  name: openshift-workload-availability
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: operators.coreos.com/v1alpha1
kind: OperatorGroup
metadata:
  name: workload-availability-operatorgroup
  namespace: openshift-workload-availability
spec:
  targetNamespaces:
    - openshift-workload-availability
---
# 1. Self-Node Remediation (SNR) Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: self-node-remediation
  namespace: openshift-workload-availability
spec:
  channel: stable
  installPlanApproval: Automatic
  name: self-node-remediation
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# 2. Node Health Check (NHC) Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-healthcheck-operator
  namespace: openshift-workload-availability
spec:
  channel: candidate
  installPlanApproval: Automatic
  name: node-healthcheck-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
